name: open_weather
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  xml: ^6.3.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  geolocator: ^10.0.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.8.0

flutter_gen:
  assets:
    enabled: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/
    - assets/logo/splashview_logo.png

